version: '3'

services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6381:6379"

  redis-slave:
    image: redis
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: ["redis-server", "--slaveof", "redis-master", "6379"]